# Generated by Django 4.1.5 on 2023-01-11 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_specialty', models.CharField(blank=True, help_text='max character is approve is 100 character, be careful ', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('date_of_birth', models.DateField(help_text='Set Your Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_history', models.TextField(blank=True, help_text='Add any patient history, max length is 255 character', max_length=255, null=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date of patient visit the doctor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalImageApp.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalImageApp.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medical Image', models.ImageField(blank=True, height_field=100, null=True, upload_to='medical_image', verbose_name='Medical Image of the patient', width_field=100)),
                ('Cypher', models.JSONField(default='', verbose_name='cypher')),
                ('cipher + Hash', models.JSONField(default='', verbose_name='hash of cypher')),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalImageApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalImageApp.userinformation'),
        ),
    ]
